
FROM python:3.8.6-buster

COPY app /app
COPY requirements.txt /requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD uvicorn #app.api:app# --host 0.0.0.0
CMD front-streamlit

#to run the container : docker run -p 8080:8000 api
